[package]
name = "snake"
version = "0.1.0"
authors = ["Jonas Wiebe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
speedy2d = "1.0.5"
rand = "0.8.3"